### ISSUE TITLE
Implement deposit snapshot API

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5697] opened 2023-06-24 11:27 UTC
### Problem description

Latest beacon API spec requires deposit snapshot API
- https://github.com/ethereum/beacon-APIs/pull/245

### Solution description

Implement the following route:
- https://ethereum.github.io/beacon-APIs/#/Beacon/getDepositSnapshot

**Comment by dapplion** [comment] 2023-06-26 05:51
- Duplicate of https://github.com/ChainSafe/lodestar/issues/4935

**Closed as completed by dapplion** 2023-06-26 05:51 UTC
Labels: meta-feature-request
