### ISSUE TITLE
Missed chain reorg event

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5818] opened 2023-07-29 08:15 UTC
### Describe the bug

There is big reorg on Goerli at slot https://goerli.beaconcha.in/slot/6172162

```
1912099:Jul-28 19:51:49.645[chain]         verbose: New chain head slot=6172159, root=0xb62d724b832fcb588ff6f590f39953337744cd1a85a4b3818ec1694deeff0c8f, delaySec=1.6449999809265137
```

```
1913209:Jul-28 19:52:29.981[chain]         verbose: New chain head slot=6172162, root=0x3a33c88767a5bfaf8cdbcd3f3e63c5eb1d913e5ca7c6f4b1e314b9440e5ba865, delaySec=5.980999946594238
```

their common ancestor is slot 6172126

Block parent distance metric was able to catch it
<img width="806" alt="Screenshot 2023-07-29 at 15 11 49" src="https://github.com/ChainSafe/lodestar/assets/10568965/fa2c5df0-3a21-4195-b369-0217b82fb38b">

however "Reorg depth" was not
<img width="783" alt="Screenshot 2023-07-29 at 15 12 30" src="https://github.com/ChainSafe/lodestar/assets/10568965/1736cb78-1814-4e17-b2b8-25191527881a">

I also wasn't able to find "Chain reorg" log https://github.com/ChainSafe/lodestar/blob/v1.9.2/packages/beacon-node/src/chain/blocks/importBlock.ts#L262

### Expected behavior

Should emit chain reorg event with depth 36

### Operating system

Linux

### Lodestar version or commit hash

v1.9.2

**Comment by twoeths** [comment] 2023-07-29 09:45
The previous reorg event from block *128 to *130 was caught by the node

```
Jul-28 19:46:03.921[chain]         verbose: Chain reorg depth=4, epoch=192879, slot=6172130, newHeadBlock=0xd8b987f72bb20c61729ad6be4cf874b81ae2b608bfc86a81a60fae855014648b, oldHeadBlock=0x9d9e825cf8d89776b9c69954fc7d13fe25bf739014a2a9642476ea7dcf93921e, newHeadState=0x4fb962bbe4d0ba356eacb1a9ebef788fe94564fc71eca964826cb04576390ce1, oldHeadState=0xad933e7b92749ad2ffb3b30e6e1e2a8e9e826ee845cfad275f71b58126996f06, executionOptimistic=false
```
also check https://forky.goerli.ethpandaops.io/ to see the reorg

**Comment by philknows** [comment] 2023-11-07 20:18
- related to #5494

**Comment by wemeetagain** [comment] 2024-10-15 16:48
closing, duplicate of #5494

**Closed as not planned by wemeetagain** 2024-10-15 16:48 UTC
Labels: scope-metrics, meta-bug
