### ISSUE TITLE
Figure out attestation aggregation

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#375] opened 2019-08-05 14:53 UTC
Right now we have no logic to aggregate attestations.
We will want a solution so we can give validator clients aggregated attestations.

Post resources, flesh out a strategy, etc here so we can figure out what the right direction for implementation is.

**Comment by mpetrunic** [comment] 2019-09-19 15:20
@

> This issue has been automatically marked as stale because it has not had recent activity. It will be closed in 7 days if no further activity occurs. Thank you for your contributions.

leave this alone

**Comment by mpetrunic** [comment] 2019-09-30 13:44
duplicate of #419

**Closed as completed by mpetrunic** 2019-09-30 13:44 UTC
