### ISSUE TITLE
Have execution addresses follow ERC55 format

### ISSUE THREAD

**Issue by jeluard** [ChainSafe/lodestar#6322] opened 2024-01-18 16:00 UTC
A recent [change](https://github.com/ethereum/beacon-APIs/pull/396) in the `beacon-APIs` specs require execution addresses to be formatted following [ERC55](https://eips.ethereum.org/EIPS/eip-55).
Make the necessary changes.

**Comment by nflaig** [comment] 2024-01-18 16:04
Closing as duplicate of https://github.com/ChainSafe/lodestar/issues/6211

**Closed as completed by nflaig** 2024-01-18 16:04 UTC
