### ISSUE TITLE
Sync status rest api method

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#407] opened 2019-08-29 12:24 UTC
Rest api for fetching sync status is currently mocked.
Sync module should implement proper method for sync status and they should be integrated in rest api.

**Comment by wemeetagain** [comment] 2019-11-26 15:25
Duplicate of #395

**Closed as completed by wemeetagain** 2019-11-26 15:25 UTC

**Comment by mpetrunic** [comment] 2019-11-26 15:27
@wemeetagain Might be good idea to expand #395 because currently it's just about implementing method in Sync module while this was related to sync status rest api

**Comment by wemeetagain** [comment] 2019-11-26 15:35
added a link to swaggerhub example in the description
