### ISSUE TITLE
API base url parsing does not work for eventstream 

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#4521] opened 2022-09-08 15:44 UTC
**Describe the bug**

If someone using a **base url** ending with `/` that make the `api.events.` namespace to not work. All other namespaces works fine. 

**Expected behavior**

It should work fine without any error by parsing the base url correctly. If not then it should throw some error to users to tell them base url format is not valid. 

**Steps to Reproduce**

```ts
import {getClient} from "@lodestar/api";

const api =  getClient({baseUrl: "http://127.0.0.1:5001/"});
```

**Desktop (please complete the following information):**

- Branch: [unstable]
- Commit hash: [e8232]

**Comment by philknows** [comment] 2023-11-05 16:04
Make sure it's not an issue after #5128

**Comment by nflaig** [comment] 2023-12-12 10:45
I have opened a PR to address this https://github.com/ChainSafe/lodestar/pull/6179 but I am not sure if we should throw an error if server responds with a 404 (which it did previously due to `//` in URL).

Right now the only errors that are considered "unrecoverable" are 400 and 500 status codes, those are also defined in the spec.
https://github.com/ChainSafe/lodestar/blob/959a8af1b757c46a0e57450788fb72773a372608/packages/api/src/beacon/client/events.ts#L36-L42

The problem is that the eventstream will be closed permanently if we reject on error here which might not be desired for 404 errors because the issue could be related to a proxy misconfiguration, same goes for 401 errors, those could be potentially recoverable and it might be safer to retry connecting the eventstream.

Even if we don't consider 401 / 404 as fatal errors we should definitely find a solution to log those errors which is currently not done as handler does not have access to logger
https://github.com/ChainSafe/lodestar/blob/959a8af1b757c46a0e57450788fb72773a372608/packages/api/src/beacon/client/events.ts#L44-L45

> If not then it should throw some error to users to tell them base url format is not valid.

The http client throws an error if base url format is invalid, the expected behavior stated in this PR should be addressed once https://github.com/ChainSafe/lodestar/pull/6179 is merged

**Closed as completed** 2023-12-12 17:27 UTC
