### ISSUE TITLE
Error on publishAggregateAndProofs

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4091] opened 2022-05-31 04:03 UTC
**Describe the bug**

Found this in Ropsten

```
370320:May-31 02:14:08.141[API]             error: Error on publishAggregateAndProofs [0] slot=3370, index=1 code=ATTESTATION_ERROR_ATTESTERS_ALREADY_KNOWN, targetEpoch=105, aggregateRoot=0x45e8defa8a743ac4bd3a38fdcef443da6734f438b0089740b3b638a20e003895
```

**Expected behavior**

due to #4019 , our published AggregateAndProof may be known to us, but we should be able to publish to the network as it could be helpful to others

**Comment by dapplion** [comment] 2022-05-31 04:40
Duplicate of https://github.com/ChainSafe/lodestar/issues/4089

**Closed as completed by dapplion** 2022-05-31 04:40 UTC
