### ISSUE TITLE
The `Infinity` parameters values are parsed as `NaN` 

### ISSUE THREAD

**Issue by nazarhussain** [ChainSafe/lodestar#4505] opened 2022-09-02 12:59 UTC
**Describe the bug**

If we configure any parameter to be `Infinity` value that is parsed as `NaN` while running the node. 

**Expected behavior**

The `Infinity` values should be parsed as `Infinity`. 

**Steps to Reproduce**

1. Create a configuration file with following; 

```ts
const rcConfig = ({
      network: "dev",
      preset: "minimal",
      dataDir: rootDir,
      rest: true,
      "rest.address": this.address,
      "rest.port": this.restPort,
      "network.allowPublishToZeroPeers": true,
      eth1: false,
      listenAddress: this.address,
      port: this.port,
      metrics: false,
      dev: true,
      "params.ALTAIR_FORK_EPOCH": String(Infinity),
      "params.BELLATRIX_FORK_EPOCH": String(Infinity),
    } as unknown) as IBeaconArgs & IGlobalArgs;
```
2. Save it as a file 
```ts
await writeFile(`${rootDir}/rc_config.json`, JSON.stringify(rcConfig, null, 2));
```
3. Start the node with it. 
```
./packages/cli/bin/lodestar.js beacon --rcConfig `${this.rootDir}/rc_config.json`
```

**Screenshots**

Because of the following mis-configuration node get following errors: 

```
Sep-01 12:40:20.005[API]             error: Req req-2e getSyncCommitteeDuties error  Empty SyncCommitteeCache
Error: Empty SyncCommitteeCache
    at SyncCommitteeCacheEmpty.get validatorIndexMap [as validatorIndexMap] (file:////lodestar/packages/state-transition/src/cache/syncCommitteeCache.ts:27:11)
    at Object.getSyncCommitteeDuties (file:///lodestar/packages/beacon-node/src/api/impl/validator/index.ts:427:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Desktop (please complete the following information):**

- OS: Mac
- Version: 13.0
- Branch: [unstable]
- Commit hash: [04030be455d111fdf85838fb59235cd197d65154]

**Comment by wemeetagain** [comment] 2022-09-03 02:52
It's an implementation detail that we represent `0xffffffffffffffff` as `Infinity`. We require the epoch to be a quoted base-10 number eg `"18446744073709551615"`

Definitely a bug tho to accept `"Infinity"` without throwing on config validation.

**Comment by dapplion** [comment] 2022-09-03 15:05
> The Infinity values should be parsed as Infinity.

This is not expected behaviour. Arguments parser should throw if it parses a number as NaN. Consumers should specify `18446744073709551615` not `Infinity`, see  https://github.com/ethereum/consensus-specs/blob/d8e74090cf33864f1956a1ee12ba5a94d21a6ac4/configs/mainnet.yaml#L49

**Comment by dapplion** [comment] 2023-05-29 07:10
Closing since Infinity is not an ok argument

**Closed as completed by dapplion** 2023-05-29 07:10 UTC
