### ISSUE TITLE
MaxListenersExceededWarning: Possible EventTarget memory leak detected.

### ISSUE THREAD

**Issue by come-maiz** [ChainSafe/lodestar#4394] opened 2022-08-11 01:07 UTC
**Describe the bug**

I'm running lodestar from the unstable branch to test mev-boost.

I'm following these instructions: https://github.com/flashbots/mev-boost/wiki/Testing/fa8b3f72058255fe394066bab285a3e6a9be92fd#lodestar

When I start it to run the beacon node, this error appears:

```
$ ./lodestar beacon --network kiln --builder.enabled --builder.urls http://127.0.0.1:18550 --jwt-secret=/home/$USER/workspace/sec
ret                                                                                                                                                                         
Aug-11 00:59:44.258[]                 info: Lodestar network=kiln, version=v0.41.0/0de0144, commit=0de01443f1f4cfa6efc12783c5783f0035e4e29f                                 
Aug-11 00:59:44.293[]                 info: Connected to LevelDB database name=/home/ubuntu/.local/share/lodestar/kiln/peerstore                                            
Aug-11 00:59:44.319[DB]               info: Connected to LevelDB database name=/home/ubuntu/.local/share/lodestar/kiln/chain-db                                             
Aug-11 00:59:51.145[]                 info: Initializing beacon state from anchor state slot=5280, epoch=165, stateRoot=0x0a100f221de872f1f39758d1fac3673beb367f07333ca7fe36
6c28123be187af
Aug-11 00:59:51.425[ETH1]             info: Starting search for terminal POW block TERMINAL_TOTAL_DIFFICULTY=20000000000000
(node:4021308) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase l
imit
(Use `node --trace-warnings ...` to show where the warning was created)
```

It is now syncing, so this error does not seem problematic so far.

**Expected behavior**

The beacon node runs with no errors shown.

**Steps to Reproduce**

Follow this instructions to compile and run:
https://github.com/flashbots/mev-boost/wiki/Testing/fa8b3f72058255fe394066bab285a3e6a9be92fd#lodestar

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version: 22.04
- Branch: unstable
- Commit hash: 0de01443f1f4cfa6efc12783c5783f0035e4e29f

```
$ ./lodestar --version
🌟 Lodestar: TypeScript Implementation of the Ethereum Consensus Beacon Chain.
  * Version: v0.41.0/0de0144
  * by ChainSafe Systems, 2018-2022
```

**Comment by dadepo** [comment] 2022-08-11 08:25
Duplicate of #3569

**Comment by g11tech** [comment] 2022-08-11 17:12
Closing as this is duplicare of #3569 as marked by @dadepo  and is pretty harmless for now

**Closed as completed by g11tech** 2022-08-11 17:12 UTC
