### ISSUE TITLE
Grandine CL < > Lodestar VC incompatibility

### ISSUE THREAD

**Issue by barnabasbusa** [ChainSafe/lodestar#6637] opened 2024-04-05 12:51 UTC
### Describe the bug

We are in the process to test cross beacon <> validator client compatibility, and found a bug when testing Grandine CL with lodestar VC. 

Lodestar reports:
```sh
Apr-05 11:27:04.125[]                error: Error proposing block slot=1, validator=0xa158…501f - Failed to produce block: validator.produceBlockV3 - Bad Request: invalid query string: unknown field `fee_recipient`, expected one of `randao_reveal`, `graffiti`, `skip_randao_verification` - Failed to produce block
Error: Failed to produce block: validator.produceBlockV3 - Bad Request: invalid query string: unknown field `fee_recipient`, expected one of `randao_reveal`, `graffiti`, `skip_randao_verification` - Failed to produce block
    at Function.assert (file:///usr/app/packages/api/src/utils/client/httpClient.ts:44:13)
    at BlockProposingService.produceBlockWrapper (file:///usr/app/packages/validator/src/services/block.ts:212:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlockProposingService.createAndPublishBlock (file:///usr/app/packages/validator/src/services/block.ts:144:29)
    at async Promise.all (index 0)
```

Grandine reports:
```sh
nothing out of the ordinary
```

Snooper between cl <> vc reports:
```sh
nothing out of the ordinary
```

cc: @pk910

### Expected behavior

I would expect all client combinations would work. 

### Steps to reproduce

config.yaml: 
```yaml
participants:
  - cl_type: grandine
    vc_type: lodestar
additional_services:
  - dora
snooper_enabled: true
global_log_level: debug
```
`kurtosis run github.com/kurtosis-tech/ethereum-package --args-file config.yaml`

### Additional context

[Current BN <> VC Compatibility list tracker](https://github.com/kurtosis-tech/ethereum-package?tab=readme-ov-file#beacon-node--validator-client-compatibility)

![Screenshot 2024-04-05 at 14 08 53](https://github.com/ChainSafe/lodestar/assets/21987084/4ba19a53-36d3-4d39-b563-3dc1f90b2fef)

### Operating system

Linux

### Lodestar version or commit hash

Version: v1.17.0/898cd90

**Comment by barnabasbusa** [comment] 2024-04-05 12:51
Cross reference of: https://github.com/grandinetech/grandine/issues/24

**Comment by sauliusgrigaitis** [comment] 2024-04-05 13:00
Any chance for Lodestar to not send this field by default? (Maybe you can send it if CLI flag is passed)

**Comment by nflaig** [comment] 2024-04-05 13:10
> Any chance for Lodestar to not send this field by default? (Maybe you can send it if CLI flag is passed)

This is definitely an issue on our end, we were sending this query param always with a boolean value, e.g. by default `skip_randao_verification=false`. We have fixed this recently https://github.com/ChainSafe/lodestar/pull/6576 but it's not yet released.

**Comment by sauliusgrigaitis** [comment] 2024-04-05 13:13
@nflaig I just noticed that @barnabasbusa mixed errors [Discord](   https://discord.com/channels/945714351841607690/945714351841607694/1225769314649636914).

The problem is actually `fee_recipient` field:

```
Apr-05 11:27:04.125[]                error: Error proposing block slot=1, validator=0xa158…501f - Failed to produce block: validator.produceBlockV3 - Bad Request: invalid query string: unknown field `fee_recipient`, expected one of `randao_reveal`, `graffiti`, `skip_randao_verification` - Failed to produce block
Error: Failed to produce block: validator.produceBlockV3 - Bad Request: invalid query string: unknown field `fee_recipient`, expected one of `randao_reveal`, `graffiti`, `skip_randao_verification` - Failed to produce block
    at Function.assert (file:///usr/app/packages/api/src/utils/client/httpClient.ts:44:13)
    at BlockProposingService.produceBlockWrapper (file:///usr/app/packages/validator/src/services/block.ts:212:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlockProposingService.createAndPublishBlock (file:///usr/app/packages/validator/src/services/block.ts:144:29)
    at async Promise.all (index 0)
  ```

**Comment by barnabasbusa** [comment] 2024-04-05 13:15
@nflaig indeed, I mixed up the issues with nimbus and grandine.  Please see the correct error message above. 

@sauliusgrigaitis good catch!

**Comment by nflaig** [comment] 2024-04-05 13:29
I am not sure we can resolve this on the Lodestar side as we have a bunch of query params that are not part of the spec but Lodestar itself uses.

https://github.com/ChainSafe/lodestar/blob/898cd903bf9d65836ac06e43740efcc5404fe615/packages/api/src/beacon/routes/validator.ts#L489-L494

It seems like all other clients just ignore extraneous query params and we should probably avoid implementing client specific workarounds.

But let's ask @g11tech who added most / all of those extra params.

**Comment by sauliusgrigaitis** [comment] 2024-04-05 13:32
@nflaig @g11tech is it the only request that you send unspec'ed parameters?

**Comment by nflaig** [comment] 2024-04-05 13:42
> @nflaig @g11tech is it the only request that you send unspec'ed parameters?

Yes, I think this is the only api. Also since we allow to produce a blinded local block, we send `execution_payload_source` as part of the response body, this has been proposed in https://github.com/ethereum/beacon-APIs/issues/387 but did not make it into block v3 api.

**Comment by barnabasbusa** [comment] 2024-04-05 14:35
Trying again with grandine's latest image (which ignores extra fields)
`ethpandaops/grandine:ignore-extra-fields-c28d828`
```sh
Apr-05 14:33:42.048[]                error: Error proposing block slot=72, validator=0x8419…5932 - Failed to produce block: validator.produceBlockV3 - Internal Server Error: {
  "id": 1,
  "jsonrpc": "2.0",
  "error": {
    "code": -32603,
    "message": "Error processing response: encountered hyper error: hyper::Error(IncompleteMessage)"
  }
} - Failed to produce block
Error: Failed to produce block: validator.produceBlockV3 - Internal Server Error: {
  "id": 1,
  "jsonrpc": "2.0",
  "error": {
    "code": -32603,
    "message": "Error processing response: encountered hyper error: hyper::Error(IncompleteMessage)"
  }
} - Failed to produce block
    at Function.assert (file:///usr/app/packages/api/src/utils/client/httpClient.ts:44:13)
    at BlockProposingService.produceBlockWrapper (file:///usr/app/packages/validator/src/services/block.ts:212:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlockProposingService.createAndPublishBlock (file:///usr/app/packages/validator/src/services/block.ts:144:29)
    at async Promise.all (index 0)
    ```

**Comment by nflaig** [comment] 2024-04-05 14:42
> Trying again with grandine's latest image (which ignores extra fields) `ethpandaops/grandine:ignore-extra-fields-c28d828`

Looks like an internal error in Grandine

**Comment by sauliusgrigaitis** [comment] 2024-04-05 15:58
@barnabasbusa @nflaig It's `skip_randao_verification=false` now. @barnabasbusa maybe you can build Lodestar image with tha t fix https://github.com/ChainSafe/lodestar/pull/6576 ?

**Comment by nflaig** [comment] 2024-04-05 16:29
> @barnabasbusa @nflaig It's `skip_randao_verification=false` now. @barnabasbusa maybe you can build Lodestar image with tha t fix #6576 ?

You can just use `chainsafe/lodestar:next` which is build from our unstable branch on every commit

**Comment by g11tech** [comment] 2024-04-08 17:27
i would request grandine @sauliusgrigaitis  to ignore the non spec params, they are essentially there because we need them for one purpose or another.

 their defaults are spec complaint (so they assume values in accordance with spec) and responses are modified only if they were requested by these non spec aware valdiators/middlewares (DVT) 

and extra response flags carry the information if they are applied as well with again defaults of those flags in spec complaint manner which again a non aware validator software for e.g. can safely ignore.

**Comment by pk910** [comment] 2024-04-08 17:50
This is fixed in latest grandine develop version :)
Grandine is now ignoring these additional parameters, so probably nothing to do from lodestar side.

**Comment by sauliusgrigaitis** [comment] 2024-04-09 06:16
We ignore not spec'ed parameters in in particular places to achieve compatibility. However, we will probably ignore it all requests later. So this can be closed I think.

**Comment by nflaig** [comment] 2024-04-09 11:51
> We ignore not spec'ed parameters in in particular places to achieve compatibility. However, we will probably ignore it all requests later. So this can be closed I think.

Great, thanks @sauliusgrigaitis, I also think this is the best behavior as it gives clients the opportunity to experiment with new configurations even if those are not part of the spec yet.


Thanks for retesting @pk910 :pray:

**Closed as completed by nflaig** 2024-04-09 11:51 UTC
Labels: scope-interop, meta-bug
