### ISSUE TITLE
keystore.json.lock issues with lodestar and nethermind. 

### ISSUE THREAD

**Issue by KeepersWay** [ChainSafe/lodestar#6449] opened 2024-02-17 23:48 UTC
### Describe the bug

validator-1  | Feb-17 17:26:53.329[]                 info: Lodestar network=mainnet, version=v1.15.1/1857a49, commit=1857a49404f2ad965025333f0f6b3422d4c1943f
validator-1  | Feb-17 17:26:53.333[]                 info: Connecting to LevelDB database path=/var/lib/lodestar/validators/validator-db
validator-1  |  ✖ Error: ENOTDIR: not a directory, rmdir '/var/lib/lodestar/validators/keystores/0xa10438cfb720250315e5a2952cf3f0e38c8806508961c5b958665b20388b0e1ff6cb18458916073766f7963047412c97/voting-keystore.json.lock'
validator-1  |     at Object.rmdirSync (node:fs:1219:11)
validator-1  |     at Object.newFs.<computed> [as rmdir] (/usr/app/node_modules/proper-lockfile/lib/adapter.js:15:42)
validator-1  |     at removeLock (/usr/app/node_modules/proper-lockfile/lib/lockfile.js:90:16)
validator-1  |     at /usr/app/node_modules/proper-lockfile/lib/lockfile.js:73:13
validator-1  |     at Object.newFs.<computed> [as stat] (/usr/app/node_modules/proper-lockfile/lib/adapter.js:20:13)
validator-1  |     at /usr/app/node_modules/proper-lockfile/lib/lockfile.js:56:20
validator-1  |     at Object.newFs.<computed> [as mkdir] (/usr/app/node_modules/proper-lockfile/lib/adapter.js:17:24)
validator-1  |     at acquireLock (/usr/app/node_modules/proper-lockfile/lib/lockfile.js:29:16)
validator-1  |     at RetryOperation._fn (/usr/app/node_modules/proper-lockfile/lib/lockfile.js:233:13)
validator-1  |     at RetryOperation.attempt (/usr/app/node_modules/retry/lib/retry_operation.js:112:8)
validator-1  | 
validator-1 exited with code 1

ENOTDIR: not a directory, rmdir '/var/lib/lodestar/validators/keystores/0xa10438cfb720250315e5a2952cf3f0e38c8806508961c5b958665b20388b0e1ff6cb18458916073766f7963047412c97/voting-keystore.json.lock'' seems to be the main error flag. 

### Expected behavior

it should either pull the keystores from the datadir or remove stale keystores and reimport it gets stuck unable to delete nor replace.

### Additional context

This is happening, using nethermind 1.25 latest release and using lodestar 1.15.1

### Operating system

Linux

### Lodestar version or commit hash

v1.15.1

**Comment by nflaig** [comment] 2024-02-18 09:44
Did this happen when upgrading from 1.15 (or lower) to 1.15.1? The only way this error can happen is during that upgrade and if your process does not shut down cleanly and leaves behind .lock files. The solution to resolve this is by manually deleting the .lock files. And once you are on 1.15.1 (or higher) this issue can't happen anymore as .lock files of keystores that are not actively in use will be considered stale even if files are left behind due to unclean shutdown (e.g. due to power loss).


~~Could you please share some details about your setup (incl. the CLI flags you have set), to figure out why your validator client is not shutting down cleanly.~~

**Edit:** As you [noted on discord](https://discord.com/channels/593655374469660673/593655641445367808/1208541732862562384) your setup is based on eth-docker but I am not sure why there would be .lock files left behind in that case as the process should be shut down cleanly. Did you have a power loss or server crash maybe?

**Comment by KeepersWay** [comment] 2024-02-18 16:37
No the shutdown was clean using commands ./ethd update and ./ethd up which only updates and replaces the images that have an updated version in the docker repository. moreover the ./ethd up command also does a clean restart of the the images that have been updated. 

**I'm trying to locate the locked json file in the home folder following the path mentioned in the error and there is no lodestar folder located within dir. not even hidden. please advice.

I have also looked for other possible locked files such as lockfile.js in usr/app/node_modules. can't find anything.

**Comment by nflaig** [comment] 2024-02-18 17:27
> No the shutdown was clean using commands ./ethd update and ./ethd up which only updates and replaces the images that have an updated version in the docker repository. moreover the ./ethd up command also does a clean restart of the the images that have been updated.

Yes, I have also confirmed that eth-docker shuts down the process cleanly. I am using it myself with Lodestar and update from 1.14.0 to 1.15.1 went smoothly. I honestly can't explain why lock files are not clean up in your case. Good news is that from v1.15.1 the lock file handling is improved and will ignore stale .lock files, so even if you have a power loss or similar, it wont be an issue.

> **I'm trying to locate the locked json file in the home folder following the path mentioned in the error and there is no lodestar folder located within dir. not even hidden. please advice.

There are two options, you either delete them by executing the command inside the container

To list keystores
```sh
docker exec -it  eth-docker-validator-1 ls /var/lib/lodestar/validators/keystores/
```
or you can remove them from the volume path on your host system
```sh
sudo ls /var/lib/docker/volumes/eth-docker_lsvalidator-data/_data/keystores
```

**Comment by KeepersWay** [comment] 2024-02-18 17:37
I attempted to use the second command and it states there is no such directory, further more I attempted to use the first command and it states the container is restarting even though all clients are running or if I attempt to do it when the clients are off line I mentioned that no such container and I get the response. Error response from daemon: No such container: eth-docker-validator-1

Still stuck and unable to delete the lock files.

**Comment by KeepersWay** [comment] 2024-02-18 17:37
Still stuck and unable to delete the lock files.

**Comment by nflaig** [comment] 2024-02-18 17:42
Oh right, first command won't work becasue your container is crashing.

I updated the second command to match default eth-docker name.

You can also figure out the host path of a volume yourself by running these commands

Get name of validator volume
```sh
docker volume ls | grep validator
```
Inspect volume (see `Mountpoint`)
```sh
docker volume inspect <volume name>
```

**Comment by KeepersWay** [comment] 2024-02-18 17:49
Great was able to locate the locked files with the latest command mentioned deleted those will post if all works well after execution and consensus catch up.

**Comment by nflaig** [comment] 2024-02-18 17:52
For anyone else having this issue, there is also a way to delete all the .lock files in a single command recursively (as noted [here](https://askubuntu.com/a/377442/888255))

List all lock files
```sh
sudo find /var/lib/docker/volumes/eth-docker_lsvalidator-data/_data -name "*.lock" -type f
```

Then delete them all if previous output looked correct
```sh
sudo find /var/lib/docker/volumes/eth-docker_lsvalidator-data/_data -name "*.lock" -type f -delete
```

**Comment by nflaig** [comment] 2024-02-18 17:56
Closing as this issue only affects older versions of Lodestar (< v1.15.1)

**Closed as completed by nflaig** 2024-02-18 17:56 UTC
Labels: meta-bug
