### ISSUE TITLE
Light Client not subscribing to events

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [ChainSafe/lodestar#5184] opened 2023-02-20 16:53 UTC
**Describe the bug**
The following [PR](https://github.com/ChainSafe/lodestar/pull/5151) updates the `subscribedEventstream` bool flag to `true` in order to prevent from double subscribing of events. **Unfortunately, this causes the light client to not subscribe to any events at all**

**Expected behavior**

- The light client should subscribe **only once** to optimistic/finality updates

**Steps to Reproduce**

1. Run the light client and notice that the heads are not updated

**Comment by nflaig** [comment] 2023-06-13 06:15
Issue seems to be resolved on the latest stable Lodestar release (v1.8.0)

**Steps to reproduce**

Fetch finalized checkpoint

```sh
curl https://lodestar-goerli.chainsafe.io/eth/v1/beacon/states/finalized/finality_checkpoints | jq ".data.finalized.root" | tr -d '"'
```

Run light client

```sh
./lodestar lightclient --network goerli --beaconApiUrl https://lodestar-goerli.chainsafe.io --checkpointRoot 0x56dab04d46366b3054d50e5854b04ed5b5f0d5d4539e9162430dc0cc558af743 --logLevel debug
```

Observe optimistic and finality header updates

```sh
Jun-13 08:10:43.366[]                debug: Started tracking the head
Jun-13 08:10:50.212[]                debug: Updated state.optimisticHeader slot=5844053
Jun-13 08:11:02.814[]                debug: Updated state.optimisticHeader slot=5844054
...
Jun-13 08:13:14.177[]                debug: Updated state.optimisticHeader slot=5844065
Jun-13 08:13:14.180[]                debug: Updated state.finalizedHeader slot=5844000
```

Also confirmed on the beacon node side, it only subscribes once, thanks to https://github.com/ChainSafe/lodestar/pull/5151.


Closing issue for now, @Daniel-K-Ivanov feel free to reopen if you are still facing this problem on latest version.

**Closed as completed by nflaig** 2023-06-13 06:15 UTC
Labels: scope-light-clients
