### ISSUE TITLE
backup eth1 node provider failover does not actually work?

### ISSUE THREAD

**Issue by timothysu** [ChainSafe/lodestar#3845] opened 2022-03-10 19:04 UTC
**Describe the bug**
When a the primary eth1 node goes down and a second eth1 node begins serving requests, the logs get littered with messages as follows:
```
error: Error updating eth1 chain cache code=ETH1_ERROR_NON_CONSECUTIVE_LOGS, newIndex=123809, prevIndex=90472

Error: ETH1_ERROR_NON_CONSECUTIVE_LOGS
    at Eth1DepositsCache.add (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositsCache.ts:48:15)
    at Eth1DepositDataTracker.updateDepositCache (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:174:5)
    at Eth1DepositDataTracker.update (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:155:33)
    at Eth1DepositDataTracker.runAutoUpdate (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:129:29)
```

**Expected behavior**
No errors (and no DB corruption?)

**Steps to Reproduce**
1. Have a fully synced node (unsure if this is required)
2. Specify two eth1 nodes with `--eth1.providerUrls`
3. Take the first of the two nodes offline and have it fall back (can be verified by seeing json rpc requests on the secondary)

**Screenshots**
n/a

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04 LTS
- Version: `chainsafe/lodestar:v0.34.1` via docker
- Branch: n/a
- Commit hash: n/a

**Comment by dapplion** [comment] 2022-03-14 03:40
@g11tech can you take a look?

**Comment by g11tech** [comment] 2022-03-14 11:06
@dapplion :+1:

**Comment by dapplion** [comment] 2022-05-10 12:16
Marking as HIGH priority since this issue can potentially lead to proposal errors in un-resolved before proposing

**Comment by twoeths** [comment] 2022-12-27 07:14
somehow there is a gap between new deposit index and old deposit index, this is strange because we always based on highest deposit event block number before fetching deposit events

if we prioritize to work on this in a Sprint, need to prepare 2 public eth1 nodes to reproduce the issue

**Comment by philknows** [comment] 2022-12-28 21:43
> somehow there is a gap between new deposit index and old deposit index, this is strange because we always based on highest deposit event block number before fetching deposit events
> 
> if we prioritize to work on this in a Sprint, need to prepare 2 public eth1 nodes to reproduce the issue

Would you be able to test against with some of the rescue nodes we have setup for production @tuyennhv ? I believe we have two from two different providers available.

**Comment by twoeths** [comment] 2023-01-02 12:12
I have a branch (`tuyen/eth1_use_fallback_url`) to switch between 2 different eth1 provider urls every 5 minutes and it still can fetch deposits successfully (this is on mainnet)

<img width="1598" alt="Screen Shot 2023-01-02 at 19 07 54" src="https://user-images.githubusercontent.com/10568965/210229224-79e2638d-5f4d-4d60-8a36-f37c1974470f.png">

also the log does not show the error in this issue
```
grep -e "ETH1_ERROR_NON_CONSECUTIVE_LOGS" -rn beacon-2023-01-02.log
```

```
grep -e "Error updating eth1 chain" -rn beacon-2023-01-02.log
```

since this issue was open for a while and code changed, I suppose we don't have it anymore.

@timothysu if you can reproduce, feel free to reopen. Thanks.

**Closed as completed by twoeths** 2023-01-02 12:12 UTC
Labels: prio-high
