### ISSUE TITLE
Error: bytes is not iterable

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3934] opened 2022-04-18 09:07 UTC
**Describe the bug**

Got this error when trying to download state 

```
curl  http://localhost:9596/eth/v2/debug/beacon/states/2785280
{"statusCode":500,"error":"Internal Server Error","message":"bytes is not iterable"}
```

Node log
```
Apr-18 11:02:36.691[API]             ^[[31merror^[[39m: Req req-186n getStateV2 error  bytes is not iterable
TypeError: bytes is not iterable
    at Object.toHexString (/usr/src/lodestar/node_modules/@chainsafe/ssz/src/util/byteArray.ts:8:22)
    at ByteVectorType.toJson (/usr/src/lodestar/node_modules/@chainsafe/ssz/src/type/byteArray.ts:112:12)
    at Object.value_toJsonArray (/usr/src/lodestar/node_modules/@chainsafe/ssz/src/type/arrayBasic.ts:174:27)
    at VectorCompositeType.toJson (/usr/src/lodestar/node_modules/@chainsafe/ssz/src/type/array.ts:124:12)
    at ContainerType.toJson (/usr/src/lodestar/node_modules/@chainsafe/ssz/src/type/container.ts:353:33)
    at Object.toJson (/usr/src/lodestar/packages/api/src/utils/types.ts:141:49)
    at Object.handler (/usr/src/lodestar/packages/api/src/server/debug.ts:39:41)
```

**Expected behavior**

No error, should be able to download state with that curl command

**Comment by dadepo** [comment] 2022-04-18 14:51
This looks like a duplicate of [3872](https://github.com/ChainSafe/lodestar/issues/3872)

**Closed as completed** 2022-04-25 13:28 UTC
