### ISSUE TITLE
When using --checkpointsync if the flag isn't at the head (see image) the sync download fails

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4524] opened 2022-09-08 19:49 UTC
**Describe the bug**

Lodestar is unable to fetch a weak subjectivity state if the checkpoint fetched is not at the head. It returns:

```
Sep 08 07:10:37 ETH-STAKER-001 lodestar[2124]: Sep-08 07:10:37.676[]                 info: Fetching weak subjectivity state weakSubjectivityServerUrl=https://goerli.beaconstate.info
Sep 08 07:10:38 ETH-STAKER-001 lodestar[2124]:  ✖ Error: Unable to fetch weak subjectivity state: Internal Server Error: block not found
Sep 08 07:10:38 ETH-STAKER-001 lodestar[2124]:     at fetchWeakSubjectivityState (file:///usr/local/bin/lodestar/packages/cli/src/networks/index.ts:157:11)
Sep 08 07:10:38 ETH-STAKER-001 lodestar[2124]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Sep 08 07:10:38 ETH-STAKER-001 lodestar[2124]:     at fetchWSStateFromBeaconApi (file:///usr/local/bin/lodestar/packages/cli/src/cmds/beacon/initBeaconState.ts:169:35)
Sep 08 07:10:38 ETH-STAKER-001 lodestar[2124]:     at initBeaconState (file:///usr/local/bin/lodestar/packages/cli/src/cmds/beacon/initBeaconState.ts:100:12)
Sep 08 07:10:38 ETH-STAKER-001 lodestar[2124]:     at Object.beaconHandler [as handler] (file:///usr/local/bin/lodestar/packages/cli/src/cmds/beacon/handler.ts:59:41)
Sep 08 07:10:38 ETH-STAKER-001 systemd[1]: lodestarbeacon.service: Main process exited, code=exited, status=1/FAILURE
Sep 08 07:10:38 ETH-STAKER-001 systemd[1]: lodestarbeacon.service: Failed with result 'exit-code'.
```

**Expected behavior**

Lodestar should be able to take any recent checkpoint for checkpointsync from a sync URL.

**Screenshots**

Flag is not at head. Fetch fails.

![checkpoint](https://user-images.githubusercontent.com/58080811/189212928-764a07a1-afb9-479a-90d0-461063ee0ab1.png)

**Comment by g11tech** [comment] 2022-09-10 20:42
This error seemed to be have thrown the URL from where its being synced, its *should* not be a problem with lodestar but worth checking out

**Comment by SomerEsat** [comment] 2022-09-10 23:29
Agreed. It seems like more of an issue with the checkpointsync provider. However - should the Lodestar client be more resilient to that sort of condition? E.g. As Phil suggests above, rather than error out, it could look back for the previous N blocks and then error out if not found.

One other thing to consider is that some clients will ignore the checkpointsync setting if the beacon chain DB exists. In Lodestar's case, it seems to do the download each time the client is restarted. One option could be to ignore the sync if the DB exists. Another could be to check the local DB current head against network current head, and if far back, execute the sync. But that may be too complicated/error prone.

**Comment by dapplion** [comment] 2022-09-12 09:33
This is a good point. Lodestar current logic is if `existing_db_last_state.slot < checkpoint_sync_state.slot`, then use the checkpoint sync state. We should change that to `existing_db_last_state.slot < checkpoint_sync_state.slot - offset` where offset is configurable parameter that default to the weak subjectivity period

**Comment by yorickdowne** [comment] 2023-01-06 15:04
This issue would be worth resurrecting. Just tried it with `goerli.beaconstate.info` and am running into this.

```
eth-docker-devel-consensus-1  | Checkpoint sync enabled
eth-docker-devel-consensus-1  | Jan-06 15:02:04.142[]                 info: Lodestar network=goerli, version=v1.3.0/031e42c, commit=031e42cbe8015109e2af6e9cdec1b15dd66fc937
eth-docker-devel-consensus-1  | Jan-06 15:02:04.161[]                 info: Connected to LevelDB database path=/var/lib/lodestar/consensus/chain-db
eth-docker-devel-consensus-1  | Jan-06 15:02:04.166[]                 info: Fetching checkpoint state checkpointSyncUrl=https://goerli.beaconstate.info
eth-docker-devel-consensus-1  |  ✖ Error: Unable to fetch weak subjectivity state: Internal Server Error: block not found
eth-docker-devel-consensus-1  |     at fetchWeakSubjectivityState (file:///usr/app/packages/cli/src/networks/index.ts:157:11)
eth-docker-devel-consensus-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
eth-docker-devel-consensus-1  |     at fetchWSStateFromBeaconApi (file:///usr/app/packages/cli/src/cmds/beacon/initBeaconState.ts:194:35)
eth-docker-devel-consensus-1  |     at initBeaconState (file:///usr/app/packages/cli/src/cmds/beacon/initBeaconState.ts:125:12)
eth-docker-devel-consensus-1  |     at Object.beaconHandler [as handler] (file:///usr/app/packages/cli/src/cmds/beacon/handler.ts:62:41)
```

It will eventually succeed. This may be a corner case when the provider is moving to a fresh checkpoint.

**Comment by hiromaily** [comment] 2023-01-19 08:41
What is the current status? I'm facing this issue.

**Comment by philknows** [comment] 2023-01-25 06:01
We're seeing a lot of missing states in the Goerli checkpoints @samcm and I'm unsure why this is happening. It's not just our checkpoint but also a continuous issue on other checkpoint providers as well. This issue may be related to it, but the checkpoint providers should also not be missing states, including the one EF Devops is hosting. Any ideas? 

![Screenshot 2023-01-24 at 10 54 56 PM](https://user-images.githubusercontent.com/58080811/214491739-3310175f-fbf3-4473-9aa7-2ba7b4b0a4a7.png)

Also please give EF Devops some time to respond since they're likely busy with the Interop this week.

**Comment by samcm** [comment] 2023-01-25 08:24
👋  I'm fairly certain that missing states/blocks in Checkpointz is due to the slot on the epoch boundary not containing a block (i.e. it directly relates to network participation). That is to say: the table in the WebUI is showing a list of epoch boundaries (every 32 slots), _not_ a list of finalized states 👍 

Since we only deal in epoch boundary slots, Checkpointz doesn't try and fetch finalized states/blocks that aren't on an epoch boundary (some clients dislike being served a finalized state that isn't on an epoch boundary) 🙏

Hope that helps 😄

**Comment by philknows** [comment] 2023-01-25 15:06
Thanks for the clarification @samcm. Looking to see if we can squeeze this into v1.4.0 or address it in a hotfix as it looks to be fairly annoying on the chance that people encounter this and have to wait an entire epoch or more to hopefully resolve it.

**Comment by g11tech** [comment] 2023-02-10 07:32
> This is a good point. Lodestar current logic is if `existing_db_last_state.slot < checkpoint_sync_state.slot`, then use the checkpoint sync state. We should change that to `existing_db_last_state.slot < checkpoint_sync_state.slot - offset` where offset is configurable parameter that default to the weak subjectivity period

ummm this seems to be already in place: we have
```typescript
if (lastDbState) {
    const config = createIBeaconConfig(chainForkConfig, lastDbState.genesisValidatorsRoot);
    const wssCheck = isWithinWeakSubjectivityPeriod(config, lastDbState, getCheckpointFromState(lastDbState));
    // All cases when we want to directly use lastDbState as the anchor state:
    //  - if no checkpoint sync args provided, or
    //  - the lastDbState is within weak subjectivity period:
    if ((!args.checkpointState && !args.checkpointSyncUrl) || wssCheck) {
      const anchorState = await initStateFromAnchorState(config, db, logger, lastDbState, {
        isWithinWeakSubjectivityPeriod: wssCheck,
        isCheckpointState: false,
      });
      return {anchorState};
    }
  }
```
so if db state is witnin the weak subjectivity perod, we just use it and don't even go for checking the slot/epoch of provided checkpoint

**Comment by g11tech** [comment] 2023-02-10 07:42
> wave I'm fairly certain that missing states/blocks in Checkpointz is due to the slot on the epoch boundary not containing a block (i.e. it directly relates to network participation). That is to say: the table in the WebUI is showing a list of epoch boundaries (every 32 slots), _not_ a list of finalized states +1
> 
> Since we only deal in epoch boundary slots, Checkpointz doesn't try and fetch finalized states/blocks that aren't on an epoch boundary (some clients dislike being served a finalized state that isn't on an epoch boundary) pray
> 
> Hope that helps smile

Ahh our current approach is get finalized checkpoint, and get block corresponding to epoch * SLOTS_PER_EPOCH but a missing first boundary block (which could be common in the goerli) can cause state fetch to fail.

Instead we should use the blockroot to fetch the state instead of using slots, that should ideally resolve the issue, will try to take take up the fix

**Comment by g11tech** [comment] 2023-02-11 11:30
Debugging into the issue and rethinking on it:

I think we are doing the right thing, the state corresponding to block's (fetched using checkpoint root) stateroot might or might not have been cached by the clients and clients should ideally have state cached/stored against a recent finalized checkpoint even if the checkpoint's blockroot doesn't belong to a bounday slot.

If a client is giving `block not found` error on state fetch on the epoch slot (checkpoint epoch * slot_per_epoch) then it means that the client is trying to lookup for the block first and then find its corresponding state, which is not a correct implementation (i think)

We need to see which client responded to this and why and discuss with the client team if the state for such a checkpoint should be available over the api 

cc @dapplion @wemeetagain @philknows

**Comment by g11tech** [comment] 2023-02-11 11:32
@philknows  also is this a problem which is coming from using a checkpoint published by checkpointz? I think not if they only publishes those checkpoints whos roots are known to perfectly lie on epoch boundary? :thinking:

**Comment by g11tech** [comment] 2023-02-11 17:09
As we jointly debugged @philknows 

the issue is when lodestar is not explicitly provided checkpoint from checkpointz (which only displays perfectly epoch boundary block checkpoints),
lodestar fetches `finalized` from the checkpoint url, and it could be (and is likely on goerli) a checkpoint whos root's block is not the `epoch boundary slot`

In such cases, some clients like seemingly `lighthouse` seems to fail serving the state on the `epoch slot`, primarliy because they might not have cached it, or might be using slot -> block -> state lookup path, and since no block actually was produced/or is part of canonical chain at that slot, they throw with: `block not found`

Its unlikely to happen with explicit checkpoints picked from checkpointz as @samcm mentioned that checkpointz servers `perfect` epoch boundary block root checkpoints.

May be this needs to be taken with appropriate client teams, since lodestar beacon node seems to be able to cache and serve such states

**Comment by nflaig** [comment] 2023-03-23 11:46
also facing this issue using `https://beaconstate-goerli.chainsafe.io` as checkpoint sync endpoint

```
Mar-23 11:43:56.214[]                 info: Lodestar network=goerli, version=v1.5.1/2115aa7, commit=2115aa7b688908472f82d3ee5d341cf314d5aff7
Mar-23 11:43:56.225[]                 info: Connected to LevelDB database path=/var/lib/data/chain-db
Mar-23 11:43:56.227[]                 info: Fetching checkpoint state checkpointSyncUrl=https://beaconstate-goerli.chainsafe.io
 ✖ Error: Unable to fetch weak subjectivity state: Internal Server Error: block not found
    at fetchWeakSubjectivityState (file:///usr/app/packages/cli/src/networks/index.ts:174:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchWSStateFromBeaconApi (file:///usr/app/packages/cli/src/cmds/beacon/initBeaconState.ts:194:35)
    at initBeaconState (file:///usr/app/packages/cli/src/cmds/beacon/initBeaconState.ts:125:12)
    at Object.beaconHandler [as handler] (file:///usr/app/packages/cli/src/cmds/beacon/handler.ts:76:41)

````

**Closed as completed** 2023-03-29 03:03 UTC
Labels: prio-high, scope-ux
