### ISSUE TITLE
BeaconAPI Spec Conformance

### ISSUE THREAD

**Issue by z3n-chada** [ChainSafe/lodestar#4063] opened 2022-05-25 15:39 UTC
**Describe the bug**
There are spec conformance issues in the BeaconAPI json-rpc endpoint.

**Expected behavior**

| API Path                                              | Inputs | Issue                                                        |
|:----------------------------------------------------- |:------ |:------------------------------------------------------------ |
| /eth/v1/beacon/states/(state)/root                    | "head" | No root key in the data field. No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/fork                 | "head" | No execution_optimistic field                                |
| /eth/v1/beacon/states/{state_id}/finality_checkpoints | "head" | No execution_optimistic field                                |
| /eth/v1/beacon/states/{state_id}/validators           | "head" | No execution_optimistic field                                |
| /eth/v1/beacon/states/{state_id}/committees           | "head" | No execution_optimistic field                                |
| /eth/v1/beacon/states/{state_id}/sync_committees      | "head" | No execution_optimistic field                                |
| /eth/v2/beacon/blocks/{block_id}                      | "head" | No execution_optimistic field                                |
| /eth/v1/beacon/headers                                | "head" | No execution_optimistic field                                |
| /eth/v1/node/syncing                                  | None   | No is_optimistic field                                       |

**Steps to Reproduce**
Use the json-rpc endpoint.

**Screenshots**

**Desktop (please complete the following information):**

- OS: N/A
- Version: N/A
- Branch: master
- Commit hash: N/A

**Comment by dapplion** [comment] 2022-05-26 03:47
Related to https://github.com/ChainSafe/lodestar/issues/3682

Tests should download the OpenAPI spec and assert responses follow its format

**Comment by dadepo** [comment] 2022-06-14 10:01
I ended up reaching for [Ajv](https://github.com/ajv-validator/ajv) to perform the validation of response object against the schema, but the problem is, the beacon-api spec does not have any of the properties of the response objects as required.

This makes it impossible (or convoluted) to perform a strict validation because a response object that misses any of the properties would still pass the validation check. 

Does anyone know if it was a _conscious design choice_ not marking the properties of the response object?

**Comment by dapplion** [comment] 2022-06-14 10:17
@dadepo SSZ fromJson already does property validation for all important data structures on the ingress side at runtime

To ensure we conform with the spec on output, just generate testers from the OpenAPI schema and via tests check that we conform to that spec at test runtime

- https://github.com/ChainSafe/lodestar/issues/3682

**Comment by dadepo** [comment] 2022-06-14 11:35
> just generate testers from the OpenAPI schema

@dapplion do you by chance have any tool in mind that does this? The ones I see are for either [generating client libraries](https://openapi-generator.tech/) from the OpenAPI schema, or [this paid tool](https://swagger.io/solutions/api-testing/) that offers help with testing.

The only way I found to validate the response is to use a tool like Ajv to check that the response from the API conforms to the OpenAPI spec.

**Comment by dapplion** [comment] 2022-06-14 11:38
> > just generate testers from the OpenAPI schema
> 
> @dapplion do you by chance have any tool in mind that does this? The ones I see are for either [generating client libraries](https://openapi-generator.tech/) from the OpenAPI schema, or [this paid tool](https://swagger.io/solutions/api-testing/) that offers help with testing.
> 
> The only way I found to validate the response is to use a tool like Ajv to check that the response from the API conforms to the OpenAPI spec.

https://www.google.com/search?q=openapi+to+json+schema+converter

https://github.com/openapi-contrib/openapi-schema-to-json-schema

Using generated client libraries may also work but may be more complicated

**Comment by dadepo** [comment] 2022-06-14 11:53
> https://github.com/openapi-contrib/openapi-schema-to-json-schema

This does not generate testers though, but converts OpenAPI 3.0 to JSON Schema Draft 4. The output of the conversion, can't also be used directly for comparison in tests. As the tests needs to validate that the json returned by the API is the same as what is specified in the spec. 

> Using generated client libraries may also work but may be more complicated

I'll check this out but I am not sure how that will work, The client libraries will be generated client code that calls the API, they might not have facility to validate the response. And we do not need client code to call the api as we have that already in lodestar itself.

**Comment by dapplion** [comment] 2022-12-24 03:35
- Since https://github.com/ChainSafe/lodestar/pull/4493 Lodestar is now guaranteed to conform to the JSON schema from OpenAPI spec's definition at the commit set in
https://github.com/ChainSafe/lodestar/blob/6a37cca422c5e6b819d123e0dd456ee994e08346/packages/api/test/unit/beacon/oapiSpec.test.ts#L26

Closing for now, tho note there is still work to do to ensure Lodestar _logically_ conforms to the spec.

**Closed as completed by dapplion** 2022-12-24 03:35 UTC
Labels: prio-high
