### ISSUE TITLE
api: `consensusClient.debug.getStatev2` returns incorrect BeaconState object

### ISSUE THREAD

**Issue by ratankaliani** [ChainSafe/lodestar#5737] opened 2023-07-08 00:28 UTC
### Describe the bug

I'm currently working with the @lodestar/api package to retrieve `BeaconState` from a consensus node, but it is returning an incomplete `BeaconState` object for `capella` blocks. The objects are fairly large, so I haven't been able to determine which specific containers are malformed, but when I query my consensus node directly over JSON-RPC for the `/eth/v2/debug/beacon/states/{state_id}` endpoint, I get the correct `BeaconState` object.

Specifically, I am querying for `BeaconState` and `BeaconBlock` for slot 6491104 and getting the following response:

```
BeaconBlock root:  0x8326162ea811c76d3135e60d9f0a86805a0b9c756da9fb9d7268535f46810474
BeaconState root:  0xa1dd17accf33890f0821570dde3c1a96beec5e722c108467e84c7182e5eadc99
stateRoot container in BeaconBlock: 0xa92c974e16b3fb3a081db8beb8190f1e05daedac13b598c41ce0be4f86defa64
```

The `BeaconState` root and `stateRoot` container in `BeaconBlock` should be equivalent for the same slot.

### Expected behavior

The `stateRoot` container in `BeaconBlock` should match the root hash of the `BeaconState` container.

### Steps to reproduce

1. Query `BeaconState` using the @lodestar/api package with `consensusClient.debug.getStateV2(slot)`
2. Query `BeaconBlock` using the @lodestar/api package with `consensusClient.beacon.getBlockV2(slot)`
3. Check if `BeaconState` root hash == `stateRoot` container in `BeaconBlock`

### Operating system

macOS

### Lodestar version or commit hash

v1.9.1

**Comment by nflaig** [comment] 2023-07-08 13:53
Thanks for the detailed report.

I tried to reproduce this but the result looks as expected for me

```js
import { toHexString } from "@chainsafe/ssz";
import { getClient, ApiError } from "@lodestar/api";
import { config } from "@lodestar/config/default";
import { ssz } from "@lodestar/types";

const api = getClient({ baseUrl: "http://localhost:9596" }, { config });
const slot = process.argv[2];

const blockRes = await api.beacon.getBlockV2(slot);
ApiError.assert(blockRes);

const blockStateRoot = toHexString(blockRes.response.data.message.stateRoot);
console.log("BeaconBlock stateRoot:    ", blockStateRoot);

const stateRes = await api.debug.getStateV2(slot);
ApiError.assert(stateRes);

const stateRoot = toHexString(ssz.capella.BeaconState.hashTreeRoot(stateRes.response.data));
console.log("BeaconState hashTreeRoot: ", stateRoot);

console.assert(stateRoot === blockStateRoot);
```

```sh
> node index.js 6832476
BeaconBlock stateRoot:     0xa80fa56b5f84f323e97eeb10b642190f2fb03b964eca38616e85e6c6e465bf26
BeaconState hashTreeRoot:  0xa80fa56b5f84f323e97eeb10b642190f2fb03b964eca38616e85e6c6e465bf26

> node index.js 6833329
BeaconBlock stateRoot:     0xc6bf36c98decce99faf8c06a6491de3552daad8cc8f94f216bcd55a3be0ba4ee
BeaconState hashTreeRoot:  0xc6bf36c98decce99faf8c06a6491de3552daad8cc8f94f216bcd55a3be0ba4ee

> node index.js 6833350
BeaconBlock stateRoot:     0xab26e7b7811b8c48e94edb0d4f2ab3e38969416c47f30b08dcd6a50c472790e4
BeaconState hashTreeRoot:  0xab26e7b7811b8c48e94edb0d4f2ab3e38969416c47f30b08dcd6a50c472790e4
```

I have checked multiple slots and the results are always correct. Might be an issue with the data for specific slot 6491104 you checked.

From where are you pulling the historic state and is it a Lodestar beacon node?

**Comment by ratankaliani** [comment] 2023-07-08 17:41
I'm pulling the historical state from a Prysm beacon node, so the cross-compatibility here might be the issue. It's a bit odd, as when I query for the specific RPC URL, I get the correct `BeaconState`, so this is probably an issue with deserializing responses from different consensus node implementations using the `getStateV2` method.

**Comment by nflaig** [comment] 2023-07-08 18:46
What `version` does Prysm return in `/eth/v2/debug/beacon/states/{state_id}` response?

**Comment by ratankaliani** [comment] 2023-07-10 05:21
I get `capella` so a bit confused.

**Comment by nflaig** [comment] 2023-07-10 11:33
> so the cross-compatibility here might be the issue

I reviewed our implementation and I really don't see how this would fail, if the implementations compute a different state root it would lead to a consensus failure.

I tested slot 6491104 specifically against different implementations, results are consistent.

Lighthouse
```sh
> node index.js 6491104
BeaconBlock stateRoot:     0xa92c974e16b3fb3a081db8beb8190f1e05daedac13b598c41ce0be4f86defa64
BeaconState hashTreeRoot:  0xa92c974e16b3fb3a081db8beb8190f1e05daedac13b598c41ce0be4f86defa64
```
Nimbus
```sh
> node index.js 6491104
BeaconBlock stateRoot:     0xa92c974e16b3fb3a081db8beb8190f1e05daedac13b598c41ce0be4f86defa64
BeaconState hashTreeRoot:  0xa92c974e16b3fb3a081db8beb8190f1e05daedac13b598c41ce0be4f86defa64
```

I don't have a Prysm archive node at hand to quickly test against, what are the results if you run the script I linked above (https://github.com/ChainSafe/lodestar/issues/5737#issuecomment-1627305176)?

Would be helpful if you could provide a snippet of your code, maybe something is going wrong there.

**Comment by ratankaliani** [comment] 2023-07-10 17:10
When I run the script above I get:

```
> node index.js 6491104
BeaconBlock stateRoot:     0xa92c974e16b3fb3a081db8beb8190f1e05daedac13b598c41ce0be4f86defa64
BeaconState hashTreeRoot:  0xa1dd17accf33890f0821570dde3c1a96beec5e722c108467e84c7182e5eadc99
Assertion failed
```
```
> node index.js 6832476
BeaconBlock stateRoot:     0xa80fa56b5f84f323e97eeb10b642190f2fb03b964eca38616e85e6c6e465bf26
BeaconState hashTreeRoot:  0x39b11c8bfe377623a15926db3d8e249af34d503351560a2dd1864d4580a6823d
Assertion failed
```
```
> node index.js 6833329
BeaconBlock stateRoot:     0xc6bf36c98decce99faf8c06a6491de3552daad8cc8f94f216bcd55a3be0ba4ee
BeaconState hashTreeRoot:  0xd6e6f604dde0cc296e4f567c6f158cee804825894ea1b35aafc5c4aebf8f3c77
Assertion failed
```
The state roots from the prysm node are consistently incorrect when using `@lodestar/api`. When I query the node directly at `/eth/v2/debug/beacon/states/{state_id}` endpoint, I get the correct BeaconState object.

Code I'm running is creating SSZ proofs against the `BeaconBlock` and `BeaconState`, but because of this issue, is running into difficulty equivocating the `stateRoot` from a `BeaconBlock` (as it does not match the root of the `BeaconState` of the same slot).

**Comment by nflaig** [comment] 2023-07-11 11:30
I have set up a Prysm node now to try and reproduce this. For slot **6853637** these are my results:

Fetched state using curl
```sh
curl -o prysm-6853637.json http://<prysm-node>/eth/v2/debug/beacon/states/6853637
```

Read and compute state root
```js
import fs from "fs";
import { toHexString } from "@chainsafe/ssz";
import { ssz } from "@lodestar/types";

const json = fs.readFileSync("./prysm-6853637.json");
const parsed = JSON.parse(json);
const state = ssz.capella.BeaconState.fromJson(parsed.data);

const stateRoot = toHexString(ssz.capella.BeaconState.hashTreeRoot(state));
console.log("BeaconState hashTreeRoot: ", stateRoot);
```
```sh
> node from-json.js 
BeaconState hashTreeRoot:  0x84c5aa444319e61e3b22cd5a9f36af55a18209e26be7fb6fcee43b50eb3d4538
```

This produces a wrong state root, correct root is `0x09fb204ba2d3329c1a1654d07669384e3ef75857639f484215d6eb05e8a68889`.
I checked with Nimbus and Lighthouse those produce the correct result for this slot using same approach.

I looked at the json files using [diff-json.js](https://gist.github.com/nflaig/bb8f7b9361fa80394800b5da501a91ec) and Prysm returns different `historical_roots` than other clients, see [prysm-diff.json](https://gist.github.com/nflaig/c6e971cf7083fc09abcb380e8c997ccc). It seems to me that the issue is that Prysm returns incorrect data from `/eth/v2/debug/beacon/states/{state_id}` endpoint.

I'm curious what tool you used to compute the correct state root as using  `ssz.capella.BeaconState.hashTreeRoot` consistently produces a different root.

**Comment by ratankaliani** [comment] 2023-07-12 22:07
Interesting, yeah I'm able to compute the correct state root doing the following: 

~~~typescript
const ROUTES = {
    getBlock: '/eth/v2/beacon/blocks/{block_id}',
    getGenesis: '/eth/v1/beacon/genesis',
    getHeader: '/eth/v1/beacon/headers/{block_id}',
    getBeaconState: '/eth/v2/debug/beacon/states/{state_id}',
    getSyncStatus: '/eth/v1/node/syncing'
};

type BeaconId = number | Uint8Array | string;

function toStringFromBeaconId(identifier: BeaconId) {
    if (identifier instanceof Uint8Array) {
        return toHexString(identifier);
    }
    return identifier.toString();
}

export async function getState(client: AxiosInstance, stateIdentifier: BeaconId): Promise<capella.BeaconState> {
    const id = toStringFromBeaconId(stateIdentifier);
    const response = await client.get(ROUTES.getBeaconState.replace('{state_id}', id), {
        responseType: 'arraybuffer',
        headers: {
            Accept: 'application/octet-stream'
        }
    });
    const bytes = response.data as Buffer;
    const state = ssz.capella.BeaconState.deserialize(bytes);
    return state;
} 

async function computeStateRoot(state: capella.BeaconState) {
    stateView = ssz.capella.BeaconState.toView(
            state as capella.BeaconState
        );
    console.log("stateRoot: ", toHexString(stateView.node.root))
}
~~~

**Comment by nflaig** [comment] 2023-07-13 07:53
Looks like only the json state response is invalid.

You can use @lodestar/api to get ssz response and get state root from tree view

```js
// ...
const stateRes = await api.debug.getStateV2(slot, "ssz");
ApiError.assert(stateRes);

const stateRoot = toHexString(ssz.capella.BeaconState.deserializeToView(stateRes.response).node.root);
console.log("BeaconState hashTreeRoot: ", stateRoot);
// ...
```
```sh
> node state-ssz.js 6867382
BeaconBlock stateRoot:     0x09acf082469c79474b0ba7a5331a1f44396023fca4d7673bcc149a11f1afe925
BeaconState hashTreeRoot:  0x09acf082469c79474b0ba7a5331a1f44396023fca4d7673bcc149a11f1afe925
```

I opened an issue https://github.com/prysmaticlabs/prysm/issues/12618

**Comment by ratankaliani** [comment] 2023-07-13 18:41
Awesome, ty for your help in debugging @nflaig

**Comment by nflaig** [comment] 2023-07-13 20:49
Closing as the @lodestar/api package works as expected

**Closed as completed by nflaig** 2023-07-13 20:49 UTC
