### ISSUE TITLE
Memory usage metrics panel should only track beacon node

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#5118] opened 2023-02-09 06:55 UTC
**Describe the bug**

Currently, the memory usage panel is showing data from both beacon node and validator which includes some confusing data points on the graph.

<img width="808" alt="Screenshot 2023-02-09 at 11 49 21 AM" src="https://user-images.githubusercontent.com/58080811/217739542-352302b0-0c26-46f8-a6cf-339969615f6b.png">

**Expected behavior**

For organization and simplicity, it should only be tracking beacon node memory usage.

**Comment by twoeths** [comment] 2023-02-09 06:59
this was broken after https://github.com/ChainSafe/lodestar/pull/5020

**Comment by nflaig** [comment] 2023-02-09 08:59
does the beacon node and validator use the same job? The prometheus config file needs to looks like this, with separate jobs for BN and VC

https://github.com/ChainSafe/lodestar/blob/db612ea82f618c4ab6509ebd88f96631788c93d2/prometheus.yml#L1-L12

**Comment by nflaig** [comment] 2023-02-23 15:00
This https://github.com/ChainSafe/lodestar/pull/5200 should fix all the remaining issues, the job names can now be customized when importing the dashboard. This means can just set the job name currently used and there is no longer the requirement to use `beacon` and `validator` as `job_name` as renaming jobs in prometheus config causes historical data to be lost which might not be desired.

**Comment by nflaig** [comment] 2023-03-02 08:11
The changes mention in https://github.com/ChainSafe/lodestar/issues/5118#issuecomment-1441936895 are now merged to `unstable`, let me know if there are still problems, else I would recommend that we close the issue.

**Comment by nflaig** [comment] 2023-03-04 08:37
Seems like the issue is related to how our internal prometheus instance is configured. We use the same job called `beacon` to scrape different services, including the validator client. Further details can be found [on discord](https://discord.com/channels/593655374469660673/605818244036821012/1081114490537521192).

**Comment by nflaig** [comment] 2023-03-07 08:27
I think we can close this in favor of https://github.com/ChainSafe/lodestar-ansible-development/issues/121 as the problem is not related to Lodestar or the dashboard contained in this repository.

**Comment by nflaig** [comment] 2023-05-10 13:35
Resolved by https://github.com/ChainSafe/lodestar-ansible-development/pull/141

**Closed as completed by nflaig** 2023-05-10 13:35 UTC
Labels: scope-metrics
