### ISSUE TITLE
Implement get deposit snapshot API

### ISSUE THREAD

**Issue by jeluard** [ChainSafe/lodestar#6165] opened 2023-12-07 17:53 UTC
### Problem description

Beacon API v2.4.0 spec requires get deposit snapshot API
- https://github.com/ethereum/beacon-APIs/pull/245

### Solution description

Implement the following route:
- https://ethereum.github.io/beacon-APIs/#/Beacon/getDepositSnapshot

**Comment by nflaig** [comment] 2023-12-07 17:55
- Duplicate of https://github.com/ChainSafe/lodestar/issues/5697 (see reference in issue for more context)

**Closed as completed by nflaig** 2023-12-07 17:55 UTC
